### ISSUE TITLE
Module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'

### ISSUE THREAD

**Issue by hanzh346** [AdaptiveParticles/pyapr#68]
Hi,

I meet an issue when I used the _pyapr.converter.get_apr_interactive()_ function, but this error was not raised when I changed to pyapr.converter.get_apr(). The error mostly aligns with a package named filegui.py. In 370 line of this file,:
`Traceback (most recent call last):
  File "/mnt/d/STUDY/PhD/GU/APR/APR.py", line 76, in <module>
    main()
  File "/mnt/d/STUDY/PhD/GU/APR/APR.py", line 21, in main
    brain()
  File "/mnt/d/STUDY/PhD/GU/APR/APR.py", line 59, in brain
    apr, parts = pyapr.converter.get_apr_interactive(np.squeeze(np.nan_to_num(img.astype('uint8'), 0)).astype('uint16'),
  File "/mnt/d/STUDY/PhD/GU/APR/pyapr/myenv/lib/python3.8/site-packages/pyapr/converter/converter_methods.py", line 120, in get_apr_interactive
    io_int = InteractiveIO()
  File "/mnt/d/STUDY/PhD/GU/APR/pyapr/myenv/lib/python3.8/site-packages/pyapr/utils/filegui.py", line 370, in __init__
    self.app = Qt.QtGui.QApplication.instance()
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'`

After we changed 'Qapplication' to 'app = QtWidgets.QApplication(sys.argv)', another problem showed up:

qt.qpa.plugin: Could not load the Qt platform plugin "xcb".

Is it a Qt problem in the backend?

**Comment by joeljonsson** [comment]
Hi,
Thanks for bringing this to our attention!
It appears that we need to make some changes to accommodate newer versions of `Qt` / `pyqtgraph`. 

For a quick fix in the meantime you could try installing an older version, e.g. `pip install pyqtgraph==0.12.4`. This seems to work on my system.
