### ISSUE TITLE
ModuleNotFoundError: No module named 'cmake' when Installing from source

### ISSUE THREAD

**Issue by bzufiriaki** [AdaptiveParticles/pyapr#69]
Hi, 

I am trying to install the library from source and I have installed all the dependencies needed (including CMake 3.6 or higher). However, when using `` pip install .``  I get the following error:

```

Building wheels for collected packages: pyapr
  Building wheel for pyapr (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Buildin  × Building wheel for pyapr (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\blazuf\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "C:\Users\blazuf\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "C:\Users\blazuf\Documents\APR\BrainAPR\apr\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
g wheel for pyapr (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "C:\Users\blazuf\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "C:\Users\blazuf\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "C:\Users\blazuf\Documents\APR\BrainAPR\apr\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'

```

I have tried to install it on Windows 10 and on a virtual machine Ubuntu 18.04 and I get the same error.

Has anyone had a similar issue?

Thank you very much.

**Comment by joeljonsson** [comment]
Looks like you are trying to import `cmake` from python. In that case you would first have to install the cmake python module: `pip install cmake`. This should not be necessary to install `pyapr` though, did you add any code which might have introduced this dependency?
